{
  imports = [
    ./alpha
    ./glow
    ./lazygit
    ./bufferline
    ./style
    ./clangd-extensions
    ./cmp
    ./comment
    ./copilot-lua
    ./diffview
    ./friendly-snippets
    ./harpoon
    ./indent-blankline
    ./lualine
    ./luasnip
    ./markdown-preview
    ./neo-tree
    #./neorg
    ./nix
    ./notify
    ./nvim-autopairs
    ./nvim-colorizer
    ./gitsigns
    ./surround
    ./telescope
    ./treesitter
    ./trouble
    ./twilight
    ./undotree
    ./vim-css-color
    ./which-key
  ];
}
